### ISSUE TITLE
Avoid large downloads over wifi during workshop?

### ISSUE THREAD

**Issue by bakercp** [brannondorsey/ml4music-workshop#1]
Just thinking through possible ways to avoid the long docker downloads over wifi ... ideas ...

- Have people clone it at home.
- Set up wired internet switch (?)
- Run multiple docker instances on desktops so people can use local machines via the browser, e.g. user 1, machine 1 (7006, 7007, 7008) user 2, machine 1 (8006, 8007, 8008), etc.

**Comment by brannondorsey** [comment]
1. Could work, although I wouldn't be surprised if we were making last minute updates until Sunday which could throw a wrench in that.
2. Yes! That might be our best bet. Except how many of these lame new Macs don't have ethernet ports? Will that be a problem?
3. The only thing that is exposed via a web interface is tensorboard for monitoring, but not actually running any experiments (training/generating).

How much should we expect this to be a problem? Haven't been on the school network in a while. Will it help that its a Sunday w/ very little other network activity?

**Comment by brannondorsey** [comment]
@bakercp any additional thoughts on this?

**Comment by bakercp** [comment]
I think we'll be ok on this.  We'll just stagger the downloads or have them start immediately upon arrival.

**Comment by bakercp** [comment]
There is plenty of bandwidth, the wifi gets saturated really easily though.

**Comment by brannondorsey** [comment]
It took a while but it worked.
